
# Property Types
MPI_PROP_TYPE_NONE = 0
MPI_PROP_TYPE_INT = 1
MPI_PROP_TYPE_TEXT = 2
MPI_PROP_TYPE_BINARY = 3
MPI_PROP_TYPE_OBJECT = 4
MPI_PROP_TYPE_PTR = 5
MPI_PROP_TYPE_INDEXED = 0x800

# Object types
MPI_OBJTYPE_BASE = 0x000
MPI_OBJTYPE_OBJECT = 0x1000
MPI_OBJTYPE_MAP = 0x1001
MPI_OBJTYPE_CARD = 0x1002
MPI_OBJTYPE_ADAPTER = 0x1003
MPI_OBJTYPE_CONNECTION = 0x1004
MPI_OBJTYPE_TRACE = 0x0005
MPI_OBJTYPE_ADAPTCOLL = 0x0006
MPI_OBJTYPE_MESSAGE = 0x0007
MPI_OBJTYPE_MESSAGECOLL = 0x0008
MPI_OBJTYPE_STREAMPAGE = 0x0009
MPI_OBJTYPE_STREAM = 0x000a

# Adapter types for "special" adapters
MPI_ADAPTYPE_FILE = 0
MPI_ADAPTYPE_BUFFER = 4
MPI_ADAPTYPE_DATABASE = 5
MPI_ADAPTYPE_APP = 6
MPI_ADAPTYPE_ANY = 30
MPI_ADAPTYPE_STREAM = 31
MPI_ADAPTYPE_XDS = 32
MPI_ADAPTYPE_SDO = 33
MPI_ADAPTYPE_SINK = 113

# Defines for MPIP_MAP_RUNTIME_APPLICATION
# Can be user defined also
MPIP_RT_APP_UNDEFINED = 0
MPIP_RT_APP_API = "API"
MPIP_RT_APP_CMDSVR = "CMDSERVER"
MPIP_RT_APP_LAUNCHER = "LAUNCHER"
MPIP_RT_APP_WMB = "WMB"

# Property bases
MPI_PROPBASE_OBJECT	= 0
MPI_PROPBASE_MAP = 100
MPI_PROPBASE_CARD = 200
MPI_PROPBASE_ADAPTER = 300
MPI_PROPBASE_CONNECTION = 400
MPI_PROPBASE_USER = 1000

# Base object properties
MPIP_OBJECT_ERROR_CODE = MPI_PROPBASE_OBJECT
MPIP_OBJECT_ERROR_MSG = MPI_PROPBASE_OBJECT + 1
MPIP_OBJECT_PARENT = MPI_PROPBASE_OBJECT + 2

# Adapter properties
MPIP_ADAPTER_TYPE = MPI_PROPBASE_ADAPTER 
MPIP_ADAPTER_ABBREV = MPI_PROPBASE_ADAPTER + 1
MPIP_ADAPTER_PROVIDER_CODE = MPI_PROPBASE_ADAPTER + 2
MPIP_ADAPTER_PROVIDER_MSG = MPI_PROPBASE_ADAPTER + 3
MPIP_ADAPTER_WILDCARD = MPI_PROPBASE_ADAPTER + 4
MPIP_ADAPTER_CONTEXT = MPI_PROPBASE_ADAPTER + 5
MPIP_ADAPTER_ON_SUCCESS = MPI_PROPBASE_ADAPTER + 6
MPIP_ADAPTER_ON_FAILURE = MPI_PROPBASE_ADAPTER + 7
MPIP_ADAPTER_RETRY = MPI_PROPBASE_ADAPTER + 8
MPIP_ADAPTER_RETRY_ATTEMPTS = MPI_PROPBASE_ADAPTER + 9
MPIP_ADAPTER_RETRY_INTERVAL = MPI_PROPBASE_ADAPTER + 10
MPIP_ADAPTER_SCOPE = MPI_PROPBASE_ADAPTER + 11
MPIP_ADAPTER_WARNINGS = MPI_PROPBASE_ADAPTER + 12
MPIP_ADAPTER_FETCH_UNIT = MPI_PROPBASE_ADAPTER + 13
MPIP_ADAPTER_QUANTITY = MPI_PROPBASE_ADAPTER + 14
MPIP_ADAPTER_LISTEN_TIME = MPI_PROPBASE_ADAPTER + 15
MPIP_ADAPTER_MSG_COLLECTION = MPI_PROPBASE_ADAPTER + 16
MPIP_ADAPTER_USER_DATA = MPI_PROPBASE_ADAPTER + 17
MPIP_ADAPTER_COMMANDLINE = MPI_PROPBASE_ADAPTER + 18
MPIP_ADAPTER_DATA_TO_ADAPT = MPI_PROPBASE_ADAPTER + 19
MPIP_ADAPTER_DATA_FROM_ADAPT = MPI_PROPBASE_ADAPTER + 20
MPIP_ADAPTER_LISTEN_USESAMECONN = MPI_PROPBASE_ADAPTER + 21
MPIP_ADAPTER_SQL_STMT = MPI_PROPBASE_ADAPTER + 22
MPIP_ADAPTER_TRACE_OBJECT = MPI_PROPBASE_ADAPTER + 23
MPIP_ADAPTER_NUM_MESSAGES = MPI_PROPBASE_ADAPTER + 24
MPIP_ADAPTER_DB_INFO = MPI_PROPBASE_ADAPTER + 25
MPIP_ADAPTER_GLOBAL_TX = MPI_PROPBASE_ADAPTER + 26
MPIP_ADAPTER_RES_ALIAS_HANDLE = MPI_PROPBASE_ADAPTER + 27
MPIP_ADAPTER_RES_ALIAS_SYSTEM = MPI_PROPBASE_ADAPTER + 28
MPIP_ADAPTER_ENABLE_TRANSACTIONS = MPI_PROPBASE_ADAPTER + 29
# XDS support
MPIP_ADAPTER_CALLBACK_PTR = MPI_PROPBASE_ADAPTER + 30
MPIP_ADAPTER_CAN_SET_INPUT_DATA_OBJECT = MPI_PROPBASE_ADAPTER + 31
MPIP_ADAPTER_CAN_GET_OUTPUT_DATA_OBJECT = MPI_PROPBASE_ADAPTER + 32
MPIP_ADAPTER_JNI_ENV_PTR = MPI_PROPBASE_ADAPTER + 33
MPIP_ADAPTER_EXT_DATA_HANDLER_PTR = MPI_PROPBASE_ADAPTER + 34

# Connection properties
MPIP_CONNECTION_USER_DATA = MPI_PROPBASE_CONNECTION
MPIP_CONNECTION_INUSE = MPI_PROPBASE_CONNECTION + 1
MPIP_CONNECTION_NUMBER = MPI_PROPBASE_CONNECTION + 2
MPIP_CONNECTION_TRANSACTION_COUNT = MPI_PROPBASE_CONNECTION + 3
MPIP_CONNECTION_STATE = MPI_PROPBASE_CONNECTION + 4
MPIP_CONNECTION_STATE_TIMESTAMP = MPI_PROPBASE_CONNECTION + 5
MPIP_CONNECTION_ON_SUCCESS = MPI_PROPBASE_CONNECTION + 6
MPIP_CONNECTION_ON_FAILURE = MPI_PROPBASE_CONNECTION + 7
MPIP_CONNECTION_SCOPE = MPI_PROPBASE_CONNECTION + 8
MPIP_CONNECTION_GLOBAL_TX = MPI_PROPBASE_CONNECTION + 9
MPIP_CONNECTION_MODE = MPI_PROPBASE_CONNECTION + 10

# Map properties
MPIP_MAP_MAP_NAME = MPI_PROPBASE_MAP
MPIP_MAP_INSTANCE = MPI_PROPBASE_MAP + 1
MPIP_MAP_WATCH_NUMBER = MPI_PROPBASE_MAP + 2
MPIP_MAP_GTX_CONTEXT = MPI_PROPBASE_MAP + 3
MPIP_MAP_GTX_MANAGER = MPI_PROPBASE_MAP + 4
MPIP_MAP_TRANSACTION_COUNT = MPI_PROPBASE_MAP + 5
MPIP_MAP_AUDIT_SWITCH = MPI_PROPBASE_MAP + 6
MPIP_MAP_AUDIT_BURST_DATA = MPI_PROPBASE_MAP + 7
MPIP_MAP_AUDIT_BURST_EXECUTION = MPI_PROPBASE_MAP + 8
MPIP_MAP_AUDIT_SUMMARY_EXECUTION = MPI_PROPBASE_MAP + 9
MPIP_MAP_AUDIT_SETTINGS_MAP = MPI_PROPBASE_MAP + 10
MPIP_MAP_AUDIT_SETTINGS_DATA = MPI_PROPBASE_MAP + 11
MPIP_MAP_AUDIT_LOCATION = MPI_PROPBASE_MAP + 12
MPIP_MAP_AUDIT_DIRECTORY = MPI_PROPBASE_MAP + 13
MPIP_MAP_AUDIT_DIRECTORY_CUSTOM_VALUE = MPI_PROPBASE_MAP + 14
MPIP_MAP_AUDIT_FILENAME = MPI_PROPBASE_MAP + 15
MPIP_MAP_AUDIT_FILENAME_ACTION = MPI_PROPBASE_MAP + 16
MPIP_MAP_AUDIT_FILENAME_CUSTOM_VALUE = MPI_PROPBASE_MAP + 17
MPIP_MAP_AUDIT_MEMORY_SIZED = MPI_PROPBASE_MAP + 18
MPIP_MAP_TRACE_SWITCH = MPI_PROPBASE_MAP + 19
MPIP_MAP_TRACE_LOCATION = MPI_PROPBASE_MAP + 20
MPIP_MAP_TRACE_DIRECTORY = MPI_PROPBASE_MAP + 21
MPIP_MAP_TRACE_DIRECTORY_CUSTOM_VALUE = MPI_PROPBASE_MAP + 22
MPIP_MAP_TRACE_FILENAME = MPI_PROPBASE_MAP + 23
MPIP_MAP_TRACE_FILENAME_CUSTOM_VALUE = MPI_PROPBASE_MAP + 24
MPIP_MAP_TRACE_INPUT_CONTENT = MPI_PROPBASE_MAP + 25
MPIP_MAP_TRACE_INPUT_CARD_NUMBER = MPI_PROPBASE_MAP + 26
MPIP_MAP_TRACE_INPUT_CARD_START = MPI_PROPBASE_MAP + 27
MPIP_MAP_TRACE_INPUT_CARD_END = MPI_PROPBASE_MAP + 28
MPIP_MAP_TRACE_RULES_CONTENT = MPI_PROPBASE_MAP + 29
MPIP_MAP_TRACE_RULES_CARD_NUMBER = MPI_PROPBASE_MAP + 30
MPIP_MAP_TRACE_SUMMARY_CONTENT = MPI_PROPBASE_MAP + 31
MPIP_MAP_WORKSPACE_LOCATION = MPI_PROPBASE_MAP + 32
MPIP_MAP_WORKSPACE_DIRECTORY = MPI_PROPBASE_MAP + 33
MPIP_MAP_WORKSPACE_DIRECTORY_CUSTOM = MPI_PROPBASE_MAP + 34
MPIP_MAP_WORKSPACE_FILE_PREFIX = MPI_PROPBASE_MAP + 35
MPIP_MAP_WORKSPACE_FILE_ACTION = MPI_PROPBASE_MAP + 36
MPIP_MAP_WORKSPACE_PAGING_SIZE = MPI_PROPBASE_MAP + 37
MPIP_MAP_WORKSPACE_PAGING_COUNT = MPI_PROPBASE_MAP + 38
MPIP_MAP_SLIDING_CENTURY = MPI_PROPBASE_MAP + 39
MPIP_MAP_SLIDING_CENTURY_CCLOOKUP = MPI_PROPBASE_MAP + 40
MPIP_MAP_CUSTOM_VALIDATION = MPI_PROPBASE_MAP + 41
MPIP_MAP_CV_VALIDATION_ERROR = MPI_PROPBASE_MAP + 42
MPIP_MAP_CV_RESTRICTION_ERROR = MPI_PROPBASE_MAP + 43
MPIP_MAP_CV_SIZE_ERROR = MPI_PROPBASE_MAP + 44
MPIP_MAP_CV_PRESENTATION_ERROR = MPI_PROPBASE_MAP + 45
MPIP_MAP_MAP_RETRY = MPI_PROPBASE_MAP + 46
MPIP_MAP_MAP_RETRY_ATTEMPTS = MPI_PROPBASE_MAP + 47
MPIP_MAP_MAP_RETRY_INTERVAL = MPI_PROPBASE_MAP + 48
MPIP_MAP_BURST_RESTART = MPI_PROPBASE_MAP + 49
MPIP_MAP_BURST_RESTART_ERROR_LIMIT = MPI_PROPBASE_MAP + 50
MPIP_MAP_WARNINGS_EVERY = MPI_PROPBASE_MAP + 51
MPIP_MAP_WARNINGS_14 = MPI_PROPBASE_MAP + 52
MPIP_MAP_WARNINGS_18 = MPI_PROPBASE_MAP + 53
MPIP_MAP_WARNINGS_21 = MPI_PROPBASE_MAP + 54
MPIP_MAP_WARNINGS_26 = MPI_PROPBASE_MAP + 55
MPIP_MAP_WARNINGS_27 = MPI_PROPBASE_MAP + 56
MPIP_MAP_WARNINGS_28 = MPI_PROPBASE_MAP + 57
MPIP_MAP_WARNINGS_29 = MPI_PROPBASE_MAP + 58
MPIP_MAP_BURST_NUMBER = MPI_PROPBASE_MAP + 59
MPIP_MAP_INITPENDING_HIGH = MPI_PROPBASE_MAP + 60
MPIP_MAP_INITPENDING_LOW = MPI_PROPBASE_MAP + 61
MPIP_MAP_WARNINGS_34 = MPI_PROPBASE_MAP + 62
MPIP_MAP_AUDIT_BURST_DATA_SIZE_VALIDATION = MPI_PROPBASE_MAP + 63
MPIP_MAP_DESTROY_OBJECT_POOL = MPI_PROPBASE_MAP + 64
MPIP_MAP_COMMON_TRACE_SWITCH = MPI_PROPBASE_MAP + 65
MPIP_MAP_COMMON_TRACE_ACTION = MPI_PROPBASE_MAP + 66
MPIP_MAP_COMMON_TRACE_FILE = MPI_PROPBASE_MAP + 67
MPIP_MAP_RUNTIME_APPLICATION = MPI_PROPBASE_MAP + 68
MPIP_MAP_ENABLE_TRANSACTIONS = MPI_PROPBASE_MAP + 69
MPIP_MAP_PUT_CALLBACK_PTR = MPI_PROPBASE_MAP + 70
MPIP_MAP_TRACE_CALLBACK_PTR = MPI_PROPBASE_MAP + 71
MPIP_MAP_MULTITHREADED = MPI_PROPBASE_MAP + 72
MPIP_MAP_USE_RESOURCE_MANAGER = MPI_PROPBASE_MAP + 73
MPIP_MAP_ENTITY_RESOLVER = MPI_PROPBASE_MAP + 74
MPIP_MAP_REMOTE_AUDIT = MPI_PROPBASE_MAP + 75
MPIP_MAP_REMOTE_WARNINGS = MPI_PROPBASE_MAP + 76
MPIP_MAP_RUNMAP_CALLBACK_PTR = MPI_PROPBASE_MAP + 77
MPIP_MAP_GET_CALLBACK_PTR = MPI_PROPBASE_MAP + 78
MPIP_MAP_XPATH_CALLBACK_PTR = MPI_PROPBASE_MAP + 79
MPIP_MAP_XSLT_CALLBACK_PTR = MPI_PROPBASE_MAP + 80	
MPIP_MAP_SUBST_CHARS = MPI_PROPBASE_MAP + 81	
MPIP_MAP_SUBST_LENGTH = MPI_PROPBASE_MAP + 82

# Card properties
MPIP_CARD_NAME = MPI_PROPBASE_CARD
MPIP_CARD_NUMBER = MPI_PROPBASE_CARD + 1
MPIP_CARD_DIRECTION = MPI_PROPBASE_CARD + 2
MPIP_CARD_OBJECT_COUNT = MPI_PROPBASE_CARD + 3
MPIP_CARD_BACKUP = MPI_PROPBASE_CARD + 4
MPIP_CARD_BACKUP_WHEN = MPI_PROPBASE_CARD + 5
MPIP_CARD_BACKUP_DIRECTORY = MPI_PROPBASE_CARD + 6
MPIP_CARD_BACKUP_DIRECTORY_CUSTOM_VALUE = MPI_PROPBASE_CARD + 7
MPIP_CARD_BACKUP_FILENAME = MPI_PROPBASE_CARD + 8
MPIP_CARD_BACKUP_FILENAME_CUSTOM_VALUE = MPI_PROPBASE_CARD + 9
MPIP_CARD_BACKUP_ACTION = MPI_PROPBASE_CARD + 10
MPIP_CARD_BACKUP_FILEPATH = MPI_PROPBASE_CARD + 11
MPIP_CARD_MODE = MPI_PROPBASE_CARD + 12
MPIP_CARD_REUSE_WORK_AREA = MPI_PROPBASE_CARD + 13
MPIP_CARD_DOCUMENT_VERIFICATION = MPI_PROPBASE_CARD + 14
MPIP_CARD_ERROR_CONTEXT = MPI_PROPBASE_CARD + 15
MPIP_CARD_METADATA_LOCATION = MPI_PROPBASE_CARD + 16
MPIP_CARD_ROOT_TYPE_NAME = MPI_PROPBASE_CARD + 17
MPIP_CARD_XML_NAMESPACE = MPI_PROPBASE_CARD + 18
MPIP_CARD_IS_XDS_ENABLED = MPI_PROPBASE_CARD + 19
MPIP_CARD_IS_SYNTAX	= MPI_PROPBASE_CARD + 20

# General
MPI_FALSE = 0
MPI_TRUE = 1
MPI_SWITCH_OFF = 0
MPI_SWITCH_ON = 1

# Location
MPI_LOCATION_FILE = 0
MPI_LOCATION_MEMORY	= 1

# Prefix
MPI_FILE_PREFIX_MAP	= 0
MPI_FILE_PREFIX_UNIQUE = 1

# Directory
MPI_DIRECTORY_MAP = 1
MPI_DIRECTORY_CUSTOM = 0

# File name
MPI_FILENAME_UNIQUE	= 2
MPI_FILENAME_DEFAULT = 1
MPI_FILENAME_CUSTOM	= 0

# File actions
MPI_FILE_CREATE	= 0
MPI_FILE_DELETE	= 1
MPI_FILE_APPEND	= 2

# Trace
MPI_TRACE_OFF = 0
MPI_TRACE_ALL = 1
MPI_TRACE_CARD = 2
MPI_TRACE_RANGE = 3

# MPIP_MAP_STATE
MPI_STATE_IDLE = 5
MPI_STATE_RUNNING = 6
MPI_STATE_PAUSED = 7
MPI_STATE_ABORTED = 8
MPI_STATE_FINISHED = 9

# MPIP_CARD_BACK_WHEN
MPI_WHEN_ALWAYS	= 10
MPI_WHEN_ONERROR = 11

# MPIP_CARD_MODE
MPI_MODE_INTEGRAL = 1
MPI_MODE_BURST = 0

# MPIP_ADAPTER_CONTEXT
MPI_CONTEXT_SOURCE = 14
MPI_CONTEXT_SOURCE_EVENT = 15
MPI_CONTEXT_TARGET = 16
MPI_CONTEXT_GET = 17
MPI_CONTEXT_PUT	= 18
MPI_CONTEXT_DBLOOKUP = 19
MPI_CONTEXT_DBQUERY = 20

# ADAPTER TYPES
MPI_ADAPT_TYPE_DB = 21
MPI_ADAPT_TYPE_FILE = 22
MPI_ADAPT_TYPE_MSG = 23
MPI_ADAPT_TYPE_APP = 24

# TRANSACTION MODES
MPI_TRANSACTIONS_SINGLE	= 25
MPI_TRANSACTIONS_NONE = 26
MPI_TRANSACTIONS_MULTIPLE = 27

# UNIT-OF-WORK
MPI_UNITOFWORK_MESSAGE = 28
MPI_UNITOFWORK_LOGICAL = 29

# MPIP_MAP_EVENT
MPI_EVENT_START_INPUT = 0x0001
MPI_EVENT_INPUT_COMPLETE = 0x0002
MPI_EVENT_START_OUTPUT = 0x0004
MPI_EVENT_OUTPUT_COMPLETE = 0x0008
MPI_EVENT_START_BURST = 0x0010
MPI_EVENT_BURST_COMPLETE = 0x0020
MPI_EVENT_START_MAP = 0x0040
MPI_EVENT_MAP_COMPLETE = 0x0080

MPI_EVENT_ALL = 0x00ff
MPI_EVENT_MAP_EVENTS = MPI_EVENT_START_MAP | MPI_EVENT_MAP_COMPLETE
MPI_EVENT_BURST_EVENTS = MPI_EVENT_START_BURST | MPI_EVENT_BURST_COMPLETE
MPI_EVENT_CARD_EVENTS = 0x000f

# Actions for custom validation
MPI_ACTION_CONTINUE	= 0x0000
MPI_ACTION_STOP	= 0x0001
MPI_ACTION_IGNORE = 0x0000
MPI_ACTION_VALIDATE	= 0x0001
MPI_ACTION_IGNORE_NO_WARNINGS = 0x0002
MPI_ACTION_WARN	= 0x0010
MPI_ACTION_FAIL	= 0x0020

# Actions for targets
MPI_ACTION_CREATE = 0x0001
MPI_ACTION_DONT_CREATE = 0x0002
MPI_ACTION_CREATEONCONTENT = 0x0004
MPI_ACTION_APPEND = 0x0008
MPI_ACTION_UPDATE = 0x0010

# Actions for sources
MPI_ACTION_KEEP	= 0x0001
MPI_ACTION_DELETE = 0x0002
MPI_ACTION_KEEPONCONTENT = 0x0004

# OnFailure actions
MPI_ACTION_ROLLBACK	= 0x0001
MPI_ACTION_COMMIT = 0x0002

# MPIP_ADAPTER_SCOPE
MPI_SCOPE_MAP = 0x0001
MPI_SCOPE_BURST	= 0x0002
MPI_SCOPE_CARD = 0x0004

# MPIP_CARD_DIRECTION
MPI_CARD_INPUT = 0x1
MPI_CARD_OUTPUT = 0x0

# MPIP_CARD_REUSE_WORK_AREA
MPI_WORK_AREA_REUSE	= 0x2
MPI_WORK_AREA_DONTREUSE	= 0x0

# MPIP_ADAPTER_FETCH_UNIT/MPIP_ADAPTER_QUANTITY
MPI_NUMBER_SOME = 0x0

# MPIP_ADAPTER_LISTEN_TIME
MPI_INFINITE = -1

# Global Transaction managers
MPI_TM_MQS = 1
MPI_TM_MSDTC = 2

# MPIP_CONNECTION_STATE
MPIP_CONNECTION_STATE_DOWN = 0
MPIP_CONNECTION_STATE_UP = 1

# MPIP_CARD_DOCUMENT_VERIFICATION
MPI_VERIFY_NEVER = 0
MPI_VERIFY_ALWAYS = 1
MPI_VERIFY_ONFAILURE = 2
MPI_VERIFY_ONSUCCESS = 3
MPI_VERIFY_WELLFORMED = 4

# MPIP_MAP_AUDIT_SETTINGS_MAP, MPIP_MAP_AUDIT_SETTINGS_DATA
MPI_SWITCH_NEVER = 0
MPI_SWITCH_ALWAYS = 1
MPI_SWITCH_ONERROR = 2
MPI_SWITCH_ONWARNING_ERROR = 3

# BurstAudit Data, BurstAudti Execution
MPI_AUDIT_NEVER	= 0
MPI_AUDIT_ALWAYS = 1
MPI_AUDIT_ONERROR = 2
MPI_AUDIT_ONWARNING_ERROR = 3

# Audit size validation
MPI_DATAAUDIT_WRONGSIZE = 0
MPI_DATAAUDIT_MINMAXERR	= 1

# Common trace switch
MPI_TRACE_SWITCH_DEFAULT = 1
MPI_TRACE_SWITCH_OFF = 2
MPI_TRACE_SWITCH_ON	= 3

# Common trace action
MPI_TRACE_ACTION_CREATE = 1
MPI_TRACE_ACTION_APPEND = 2

# Bases for error codes
MPIRC_TYPE_SUCCESS = 0
MPIRC_TYPE_ERROR = -1
MPIRC_TYPE_WARNING = 1
MPIRC_RC_USER_BASE = 1000

# Common success codes 
MPIRC_SUCCESS = 0

# Common warning codes (info)
MPIRC_W_NO_DATA = 1
MPIRC_W_END_OF_DATA = 2
MPIRC_W_DATA_TRUNCATED = 3

# Common Error Codes
MPIRC_E_UNKNOWN = -1
MPIRC_E_EXCEPTION = -2
MPIRC_E_FAILED = -3
MPIRC_E_INVALID_PROPERTY = -4
MPIRC_E_TYPE_MISMATCH = -5
MPIRC_E_PROPERTY_NOTSET = -6
MPIRC_E_INVALID_INDEX = -7
MPIRC_E_NULL_ARGUMENT = -8
MPIRC_E_INVALID_ARGUMENT = -9
MPIRC_E_ALLOC_FAILED = -10
MPIRC_E_NO_PROPERTIES = -11
MPIRC_E_INVALID_TYPE = -12
MPIRC_E_BAD_CONNECTION = -13
MPIRC_E_FILEOPEN_FAILED = -14
MPIRC_E_FILEWRITE_FAILED = -15
MPIRC_E_FILEREAD_FAILED = -16
MPIRC_E_FILEPOS_FAILED = -17
MPIRC_E_INVALID_OBJECT = -18
MPIRC_E_NULL_OBJECT = -19
MPIRC_E_ILLEGAL_CALL = -20
MPIRC_E_EOF = -21
MPIRC_E_ROOT_ELEM = -22
MPIRC_E_NOT_ROOT_ELEM = -23
MPIRC_E_3RD_PARTY_FAILED = -24
MPIRC_E_NON_RESIZABLE = -25
MPIRC_E_RUNMAP_FAILED = -26
MPIRC_E_LOADMAP_FAILED = -27
MPIRC_E_NONEXISTING = -28
MPIRC_E_LOADLIBRARY_FAILED = -29
MPIRC_E_INVALIDSEEK = -30
MPIRC_E_DATA_TRUNCATED = -31
MPIRC_E_NO_PARENT = -32
MPIRC_E_NOT_SUPPORTED = -33
MPIRC_XERCES_FAILED = -34
MPIRC_E_INVALID_CARDNUM = -35
MPIRC_E_INVALID_CARDDIR = -36
MPIRC_E_PROPXML_MISMATCH = -37
MPIRC_E_INVALID_PROPID = -38
MPIRC_E_INVALID_PROPTYPE = -39

# Notification IDs
MPIN_ADAPTER_GETSTART = 1
MPIN_ADAPTER_GETSTOP = 2
MPIN_ADAPTER_PUTSTART = 3
MPIN_ADAPTER_PUTSTOP = 4
MPIN_ADAPTER_LISTENSTART = 5
MPIN_ADAPTER_LISTENSTOP = 6
MPIN_ADAPTER_LISTENABORT = 7
MPIN_ADAPTER_MAPABORT = 8

# Compare type
MPI_CMP_LESS = -1
MPI_CMP_EQUAL = 0
MPI_CMP_GREATER	= 1
MPI_CMP_DIFFER = -2

MPI_COMMIT = 0
MPI_ROLLBACK = 1